set nocp
set modelines=0
set backspace=2
syntax on
autocmd InsertLeave * se nocul
autocmd InsertEnter * se cul 
set smartindent
set autoindent
set confirm
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set number
set history=100
set hlsearch
set incsearch
set gdefault
set encoding=utf-8
set fileencodings=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936,utf-16,big5,euc-jp,latin1
set guifont=Menlo:h16:cANSI
set langmenu=zn_CN.UTF-8
set helplang=cn
set ruler
set laststatus=1
set showcmd
set scrolloff=3
set showmatch
set matchtime=5
set autowrite
set wildmenu
set linespace=2
set whichwrap=b,s,<,>,[,]
filetype indent on
set foldenable
set cursorline
set magic
set ignorecase
filetype on
set background=dark
set t_Co=256
set mouse=
set backspace=indent,eol,start
set autochdir
set noerrorbells
set autoread
set wildmenu
set wildmode=longest:list,full
set paste

" yaml
autocmd FileType yaml setlocal ai ts=2 sw=2 et
" ai = auto indent "自动退格对齐
" set tabstop=2 "（ts=tabstop，即一个tab的宽度被设为2个空格辣么宽）
" set shiftwidth=2 "（sw=shiftwidth，即退格对齐以2个空格为准）
" set expandtab "（et=expandtab，将tab变成空格）
